name: cat_breeds
description: "The present repository is an implementation and use of the TheCatAPI (https://api.thecatapi.com)."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  bloc_concurrency: ^0.2.5
  cat_breeds_repository:
    path: packages/cat_breeds_repository
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  the_cat_api:
    path: packages/the_cat_api

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

  melos: ^6.1.0
  very_good_analysis: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
