name: the_cat_api
description: A Flutter implementation of the TheCatApi that uses dio and retrofit
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.1
  very_good_analysis: ^6.0.0
